// frontend/src/lib/components/SearchBar.svelte
<script lang="ts">
  import Icon from './Icon.svelte';
  import { specialSearchSuggestions } from '$lib/search/specialSuggestions';
  import { parseSearchQuery, parseSearchToken, searchTokensToQuery, searchTokenToString, type SearchToken } from '$lib/search/tokens';
  import { rankCompletionCandidates } from '$lib/utils/completionRanking';
  import { plainTagSuggestions } from '$lib/utils/tagSuggestions';
  import { isEditableShortcutTarget } from '$lib/utils/keyboard';

  type TagLike = { name?: string; tag?: string; namespace?: string; value?: string; count?: number };
  type SuggestionLike = { name: string; value?: string; count?: number };
  type MetaTagLike = { syntax: string; hint: string; requires_value: boolean };
  type SuggestionItem = {
    kind: 'namespace' | 'tag' | 'valueless' | 'value' | 'special';
    commit: string;
    ns: string;
    val: string;
    count?: number;
    hint?: string;
    partial?: boolean;
  };
  type SuggestionGroup = { head: string; items: SuggestionItem[] };

  let {
    value,
    suggestions,
    metaTags,
    tags,
    onDraftInput,
    onCommit
  } = $props<{
    value: string;
    suggestions: SuggestionLike[];
    metaTags: MetaTagLike[];
    tags: TagLike[];
    onDraftInput: (value: string) => void;
    onCommit: (value: string) => void;
  }>();

  let tokens = $state<SearchToken[]>([]);
  let draft = $state('');
  let open = $state(false);
  let active = $state(0);
  let inputRef = $state<HTMLInputElement | undefined>();
  let rootRef = $state<HTMLDivElement | undefined>();
  let lastSyncedValue = $state('');

  const tagItems = $derived(normalizeTags(tags, suggestions));
  const groups = $derived(computeSuggestions(draft, tokens, tagItems, metaTags));
  const flat = $derived(groups.flatMap((group) => group.items.map((item) => ({ ...item, group: group.head }))));

  $effect(() => {
    if (value === lastSyncedValue) return;
    tokens = parseSearchQuery(value);
    draft = '';
    open = false;
    lastSyncedValue = value;
  });

  $effect(() => {
    if (active >= flat.length) active = 0;
  });

  $effect(() => {
    const handleKeydown = (event: KeyboardEvent) => {
      if (event.key === '/' && !isEditableShortcutTarget(event.target)) {
        event.preventDefault();
        inputRef?.focus();
      }
    };
    window.addEventListener('keydown', handleKeydown);
    return () => window.removeEventListener('keydown', handleKeydown);
  });

  $effect(() => {
    if (!open) return;
    const handleMouseDown = (event: MouseEvent) => {
      if (rootRef && !rootRef.contains(event.target as Node)) open = false;
    };
    document.addEventListener('mousedown', handleMouseDown);
    return () => document.removeEventListener('mousedown', handleMouseDown);
  });

  function normalizeTags(tags: TagLike[], suggestions: SuggestionLike[]) {
    const seen = new Map<string, { tag: string; count: number }>();
    for (const tag of tags) {
      const name = tag.name ?? tag.tag ?? (tag.namespace ? `${tag.namespace}:${tag.value ?? ''}` : (tag.value ?? ''));
      if (!name || name.startsWith('@')) continue;
      seen.set(name, { tag: name, count: tag.count ?? seen.get(name)?.count ?? 0 });
    }
    for (const suggestion of suggestions) {
      if (!suggestion.name || suggestion.name.startsWith('@')) continue;
      seen.set(suggestion.name, { tag: suggestion.name, count: suggestion.count ?? seen.get(suggestion.name)?.count ?? 0 });
    }
    return [...seen.values()].sort((a, b) => b.count - a.count || a.tag.localeCompare(b.tag));
  }

  function parseTag(tag: string) {
    const colon = tag.indexOf(':');
    if (colon < 0) return { ns: '', value: tag };
    return { ns: tag.slice(0, colon), value: tag.slice(colon + 1) };
  }

  function computeSuggestions(
    draftValue: string,
    currentTokens: SearchToken[],
    items: Array<{ tag: string; count: number }>,
    metaTags: MetaTagLike[]
  ): SuggestionGroup[] {
    const tokenStrings = new Set(currentTokens.map(searchTokenToString));
    const takenPositiveTags = new Set(
      currentTokens
        .filter((token) => !token.neg)
        .map((token) => (token.ns ? `${token.ns}:${token.val}` : token.val))
    );
    const specialItems: SuggestionItem[] = specialSearchSuggestions(draftValue, [...tokenStrings], metaTags).map((item) => ({
      kind: 'special',
      ...item
    }));
    let working = draftValue.trim();
    let negPrefix = '';
    if (working.startsWith('-')) {
      negPrefix = '-';
      working = working.slice(1);
    }

    if (!working.includes(':')) {
      const result: SuggestionGroup[] = [];
      const completionItems = plainTagSuggestions(
        working,
        items.map(({ tag, count }) => ({ name: tag, count })),
        [],
        14
      )
        .filter(({ name, kind }) => kind === 'namespace' || (!takenPositiveTags.has(name) && !tokenStrings.has(`${negPrefix}${name}`)))
        .map(({ name, count, kind }) => {
          if (kind === 'namespace') {
            const ns = name.slice(0, -1);
            return {
              kind: 'namespace' as const,
              commit: `${negPrefix}${name}`,
              ns,
              val: '',
              count,
              hint: 'namespace',
              partial: true
            };
          }
          const parsed = parseTag(name);
          return {
            kind: parsed.ns ? ('tag' as const) : ('valueless' as const),
            commit: `${negPrefix}${name}`,
            ns: parsed.ns,
            val: parsed.value,
            count
          };
        });
      if (completionItems.length) result.push({ head: 'Suggestions', items: completionItems });
      if (specialItems.length) result.push({ head: 'Query', items: specialItems });
      return result;
    }

    const colon = working.indexOf(':');
    const ns = working.slice(0, colon).toLowerCase();
    const valFrag = working.slice(colon + 1).toLowerCase();
    const valueCandidates = items
      .filter(({ tag }) => {
        if (takenPositiveTags.has(tag)) return false;
        const parsed = parseTag(tag);
        if (parsed.ns.toLowerCase() !== ns) return false;
        return !valFrag || parsed.value.toLowerCase().includes(valFrag);
      })
      .map(({ tag, count }) => ({ name: parseTag(tag).value, tag, count }));
    const values = rankCompletionCandidates(valueCandidates, valFrag)
      .slice(0, 12)
      .map(({ tag, count }) => {
        const parsed = parseTag(tag);
        return { kind: 'value' as const, commit: `${negPrefix}${tag}`, ns: parsed.ns, val: parsed.value, count };
      });

    const result: SuggestionGroup[] = [];
    if (values.length) result.push({ head: `${ns}:`, items: values });
    if (specialItems.length) result.push({ head: 'Query', items: specialItems });
    return result;
  }

  function syncCommit(nextTokens: SearchToken[]) {
    tokens = nextTokens;
    const query = searchTokensToQuery(tokens);
    lastSyncedValue = query;
    onCommit(query);
  }

  function commitString(input: string) {
    const value = input.trim();
    if (!value) return;
    const token = parseSearchToken(value);
    if (!token.ns && !token.val) return;
    const key = searchTokenToString(token);
    if (tokens.some((item) => searchTokenToString(item) === key)) {
      draft = '';
      open = false;
      onDraftInput('');
      return;
    }
    draft = '';
    open = false;
    active = 0;
    onDraftInput('');
    syncCommit([...tokens, token]);
  }

  function selectSuggestion(item: SuggestionItem) {
    if (item.partial) {
      draft = item.commit;
      active = 0;
      open = true;
      onDraftInput(draft);
      inputRef?.focus();
      return;
    }
    commitString(item.commit);
  }

  function removeToken(index: number) {
    syncCommit(tokens.filter((_, tokenIndex) => tokenIndex !== index));
  }

  function clearAll() {
    draft = '';
    open = false;
    active = 0;
    onDraftInput('');
    syncCommit([]);
  }

  function handleInput(event: Event) {
    draft = (event.currentTarget as HTMLInputElement).value;
    open = Boolean(draft.trim());
    active = 0;
    onDraftInput(draft);
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'ArrowDown') {
      if (!draft.trim()) return;
      event.preventDefault();
      active = Math.min(active + 1, Math.max(flat.length - 1, 0));
      open = true;
      return;
    }
    if (event.key === 'ArrowUp') {
      if (!draft.trim()) return;
      event.preventDefault();
      active = Math.max(active - 1, 0);
      open = true;
      return;
    }
    if (event.key === 'Enter' || event.key === 'Tab') {
      if (open && flat[active]) {
        event.preventDefault();
        selectSuggestion(flat[active]);
      } else if (draft.trim()) {
        event.preventDefault();
        commitString(draft);
      }
      return;
    }
    if (event.key === 'Escape') {
      event.preventDefault();
      open = false;
      draft = '';
      onDraftInput('');
      inputRef?.blur();
      return;
    }
    if (event.key === 'Backspace' && !draft && tokens.length > 0) {
      event.preventDefault();
      removeToken(tokens.length - 1);
    }
  }
</script>

<div
  class="searchbar"
  role="combobox"
  aria-label="Search tokens"
  aria-controls="searchbar-suggestions"
  aria-expanded={open && flat.length > 0 ? 'true' : 'false'}
  aria-haspopup="listbox"
  tabindex="-1"
  bind:this={rootRef}
  onclick={() => inputRef?.focus()}
>
  <span class="searchbar-icon"><Icon name="search" size={15} /></span>
  {#each tokens as token, index}
    <span class:neg={token.neg} class="searchbar-pill">
      {#if token.neg}<span class="neg-symbol">−</span>{/if}
      {#if token.ns}<span class="ns">{token.ns}:</span>{/if}<span>{token.val}</span>
      <button class="x" type="button" aria-label={`Remove ${searchTokenToString(token)}`} onclick={() => removeToken(index)}>
        <Icon name="close" size={10} />
      </button>
    </span>
  {/each}
  <input
    bind:this={inputRef}
    class="searchbar-input"
    value={draft}
    placeholder={tokens.length === 0 ? 'tag, namespace:value, -exclude — try "subject:" or "hero"' : ''}
    spellcheck="false"
    autocapitalize="off"
    autocomplete="off"
    aria-label="Search library"
    oninput={handleInput}
    onfocus={() => (open = Boolean(draft.trim()))}
    onkeydown={handleKeydown}
  />
  {#if tokens.length > 0 || draft}
    <button class="searchbar-clear" type="button" aria-label="Clear search" title="Clear search" onclick={clearAll}>
      <Icon name="close" size={13} />
    </button>
  {/if}

  {#if open && draft.trim() && flat.length > 0}
    <ul id="searchbar-suggestions" class="search-suggestions" role="listbox" aria-label="Search suggestions" onmousedown={(event) => event.preventDefault()}>
      {#each groups as group, groupIndex}
        {@const offset = groups.slice(0, groupIndex).reduce((sum, item) => sum + item.items.length, 0)}
        <li class="group-head">
          <span>{group.head}</span>
          <span>{group.items.length}</span>
        </li>
        {#each group.items as item, itemIndex}
          {@const flatIndex = offset + itemIndex}
          <li role="presentation">
            <button
              class:is-active={flatIndex === active}
              type="button"
              role="option"
              aria-selected={flatIndex === active}
              onmouseenter={() => (active = flatIndex)}
              onclick={() => selectSuggestion(item)}
            >
              <span class="tok">
                {#if item.ns}<span class="ns">{item.ns}:</span>{/if}<span>{item.val}</span>
              </span>
              {#if item.hint}<span class="hint">{item.hint}</span>{/if}
              {#if item.count != null}<span class="count">{item.count.toLocaleString()}</span>{/if}
            </button>
          </li>
        {/each}
      {/each}
      <li class="search-suggestions-footer">
        <span class="keys">
          <span><span class="g-kbd">↑</span><span class="g-kbd">↓</span> navigate</span>
          <span><span class="g-kbd">↵</span> select</span>
          <span><span class="g-kbd">Esc</span> close</span>
        </span>
        <span>prefix <span class="g-kbd">-</span> to exclude</span>
      </li>
    </ul>
  {/if}
</div>

// temp/gooru-concept-ui/components/SearchBar.jsx
// SearchBar — inline pills + IDE-style autocomplete dropdown.
//
// A "token" is one of:
//   namespace:value   →   { ns: 'subject', val: 'portrait', neg: false }
//   -namespace:value  →   { ns: 'subject', val: 'portrait', neg: true  }
//   @flag             →   { ns: '@',       val: 'favorite', neg: false }
//   bare-word         →   { ns: '',        val: 'roll',     neg: false }
//
// Tokens commit on Enter / Tab / suggestion click. Backspace on an empty
// input removes the last pill. Suggestions update as you type and adapt
// to whether you've typed past a `:` (then we suggest values within that
// namespace).

const {useState: _useSS, useRef: _useRS, useEffect: _useES, useMemo: _useMS} = React;

function parseToken(s) {
  let neg = false;
  if (s.startsWith('-')) { neg = true; s = s.slice(1); }
  const i = s.indexOf(':');
  if (i < 0) return {ns: '', val: s, neg};
  return {ns: s.slice(0, i), val: s.slice(i + 1), neg};
}
function tokenToString(t) {
  const body = t.ns ? t.ns + ':' + t.val : t.val;
  return (t.neg ? '-' : '') + body;
}

// Stable list of known namespaces (with totals)
function buildNamespaceCounts() {
  const map = {};
  TAG_INDEX.forEach(({tag, count}) => {
    const {ns} = parseTag(tag);
    if (!ns) return;
    map[ns] = (map[ns] || 0) + count;
  });
  return Object.entries(map).sort((a, b) => b[1] - a[1]).map(([ns, count]) => ({ns, count}));
}
const ALL_NAMESPACES = buildNamespaceCounts();
const VALUELESS_TAGS = TAG_INDEX.filter(t => !t.tag.includes(':'));

function highlight(text, term) {
  if (!term) return text;
  const i = text.toLowerCase().indexOf(term.toLowerCase());
  if (i < 0) return text;
  return (
    <>{text.slice(0, i)}<span className="match">{text.slice(i, i + term.length)}</span>{text.slice(i + term.length)}</>
  );
}

function computeSuggestions(draft, tokens) {
  const takenStrings = new Set(tokens.map(tokenToString));
  const takenBareValues = new Set(tokens.filter(t => !t.neg).map(t => `${t.ns}:${t.val}`));
  const draftRaw = draft;
  let working = draft;
  let negPrefix = '';
  if (working.startsWith('-')) { negPrefix = '-'; working = working.slice(1); }

  // CASE A — no colon yet: suggest namespaces + tag matches (value'd or valueless)
  if (!working.includes(':')) {
    const term = working.toLowerCase();
    const groups = [];

    // Namespace suggestions
    const nses = ALL_NAMESPACES
      .filter(({ns}) => !term || ns.toLowerCase().startsWith(term))
      .slice(0, 6)
      .map(({ns, count}) => ({
        kind: 'namespace',
        commit: negPrefix + ns + ':',
        label: <><span className="ns">{highlight(ns, term)}:</span></>,
        hint: 'namespace',
        count,
        partial: true, // selecting this only fills the draft; doesn't commit yet
      }));
    if (nses.length) groups.push({head: 'Namespaces', items: nses});

    // Tag matches — both value'd (subject:portrait) and valueless (review)
    if (term.length >= 1) {
      const tags = TAG_INDEX
        .filter(({tag}) => {
          if (takenBareValues.has(tag)) return false;
          const {value} = parseTag(tag);
          return value.toLowerCase().includes(term);
        })
        .slice(0, 8)
        .map(({tag, count}) => {
          const {ns, value} = parseTag(tag);
          return {
            kind: ns ? 'tag' : 'valueless',
            commit: negPrefix + tag,
            label: ns
              ? <><span className="ns">{ns}:</span>{highlight(value, term)}</>
              : <span>{highlight(value, term)}</span>,
            count,
          };
        });
      if (tags.length) groups.push({head: 'Tags', items: tags});
    } else {
      // Empty draft: surface the most-used valueless tags as a quick-pick
      const vs = VALUELESS_TAGS.filter(t => !takenStrings.has(t.tag)).slice(0, 5).map(({tag, count}) => ({
        kind: 'valueless',
        commit: negPrefix + tag,
        label: <span>{tag}</span>,
        count,
      }));
      if (vs.length) groups.push({head: 'Valueless', items: vs});
    }

    return groups;
  }

  // CASE B — colon present: suggest values inside that namespace
  const ci = working.indexOf(':');
  const ns = working.slice(0, ci).toLowerCase();
  const valFrag = working.slice(ci + 1).toLowerCase();

  const tags = TAG_INDEX
    .filter(({tag}) => {
      if (tag.startsWith('@')) return false;
      const p = parseTag(tag);
      if (p.ns.toLowerCase() !== ns) return false;
      if (takenBareValues.has(tag)) return false;
      if (valFrag && !p.value.toLowerCase().includes(valFrag)) return false;
      return true;
    })
    .slice(0, 12)
    .map(({tag, count}) => {
      const p = parseTag(tag);
      return {
        kind: 'value',
        commit: negPrefix + tag,
        label: <><span className="ns">{p.ns}:</span>{highlight(p.value, valFrag)}</>,
        count,
      };
    });

  return tags.length ? [{head: `${ns}:`, items: tags}] : [];
}

function flattenSuggestions(groups) {
  const arr = [];
  groups.forEach(g => g.items.forEach(it => arr.push({...it, group: g.head})));
  return arr;
}

function SearchBarPill({token, onRemove}) {
  return (
    <span className={"searchbar-pill" + (token.neg ? ' neg' : '')}>
      {token.neg && <span style={{opacity: 0.7}}>−</span>}
      {token.ns
        ? <><span className="ns">{token.ns}:</span><span>{token.val}</span></>
        : <span>{token.val}</span>}
      <button className="x" onClick={() => onRemove()} type="button" aria-label="Remove">
        <Icon name="close" size={10}/>
      </button>
    </span>
  );
}

function SearchBar({tokens, setTokens, iconStyle, placeholder}) {
  const [draft, setDraft] = _useSS('');
  const [open, setOpen] = _useSS(false);
  const [active, setActive] = _useSS(0);
  const inputRef = _useRS(null);
  const rootRef = _useRS(null);

  // Global `/` to focus
  _useES(() => {
    const h = (e) => {
      if (e.key === '/' && document.activeElement && document.activeElement.tagName !== 'INPUT') {
        e.preventDefault();
        inputRef.current && inputRef.current.focus();
      }
    };
    window.addEventListener('keydown', h);
    return () => window.removeEventListener('keydown', h);
  }, []);

  // Close dropdown on outside click
  _useES(() => {
    if (!open) return;
    const h = (e) => {
      if (rootRef.current && !rootRef.current.contains(e.target)) setOpen(false);
    };
    document.addEventListener('mousedown', h);
    return () => document.removeEventListener('mousedown', h);
  }, [open]);

  const groups = _useMS(() => computeSuggestions(draft, tokens), [draft, tokens]);
  const flat = _useMS(() => flattenSuggestions(groups), [groups]);

  // Keep active index in bounds
  _useES(() => { if (active >= flat.length) setActive(0); }, [flat.length]);

  const commitString = (s) => {
    s = s.trim();
    if (!s) return;
    const t = parseToken(s);
    if (!t.val && !t.ns) return;
    // Dedupe by serialised form
    const key = tokenToString(t);
    if (tokens.some(x => tokenToString(x) === key)) return;
    setTokens([...tokens, t]);
    setDraft('');
    setActive(0);
  };

  const onSuggestionSelect = (sugg) => {
    if (sugg.partial) {
      // Namespace completion — fill draft, keep open
      setDraft(sugg.commit);
      setActive(0);
      inputRef.current && inputRef.current.focus();
      return;
    }
    commitString(sugg.commit);
  };

  const onKeyDown = (e) => {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setActive(a => Math.min(a + 1, flat.length - 1));
      setOpen(true);
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setActive(a => Math.max(a - 1, 0));
      setOpen(true);
    } else if (e.key === 'Enter' || e.key === 'Tab') {
      if (open && flat[active]) {
        e.preventDefault();
        onSuggestionSelect(flat[active]);
      } else if (draft.trim()) {
        e.preventDefault();
        commitString(draft);
      }
    } else if (e.key === 'Escape') {
      setOpen(false);
      setDraft('');
    } else if (e.key === 'Backspace' && draft === '' && tokens.length > 0) {
      e.preventDefault();
      setTokens(tokens.slice(0, -1));
    }
  };

  const removeToken = (i) => setTokens(tokens.filter((_, idx) => idx !== i));
  const clearAll = () => { setTokens([]); setDraft(''); setActive(0); };

  return (
    <div className="searchbar" ref={rootRef}
         onClick={() => inputRef.current && inputRef.current.focus()}>
      <span className="searchbar-icon"><Icon name="search" size={15} style={iconStyle}/></span>
      {tokens.map((t, i) => (
        <SearchBarPill key={i} token={t} onRemove={() => removeToken(i)}/>
      ))}
      <input
        ref={inputRef}
        className="searchbar-input"
        placeholder={tokens.length === 0 ? (placeholder || 'tag, namespace:value, -exclude — try "subject:" or "hero"') : ''}
        value={draft}
        spellCheck="false"
        autoCapitalize="off"
        autoComplete="off"
        onChange={(e) => { setDraft(e.target.value); setOpen(true); setActive(0); }}
        onFocus={() => setOpen(true)}
        onKeyDown={onKeyDown}
      />
      {(tokens.length > 0 || draft) && (
        <button className="searchbar-clear" type="button" onClick={(e) => {e.stopPropagation(); clearAll();}} title="Clear search">
          <Icon name="close" size={13} style={iconStyle}/>
        </button>
      )}

      {open && flat.length > 0 && (
        <ul className="search-suggestions" onMouseDown={(e) => e.preventDefault()}>
          {groups.map((g, gi) => {
            const offset = groups.slice(0, gi).reduce((a, x) => a + x.items.length, 0);
            return (
              <React.Fragment key={g.head + gi}>
                <li className="group-head" style={{cursor: 'default'}}>
                  <span>{g.head}</span>
                  <span>{g.items.length}</span>
                </li>
                {g.items.map((it, i) => {
                  const flatIdx = offset + i;
                  return (
                    <li key={it.commit + i}
                        className={flatIdx === active ? 'is-active' : ''}
                        onMouseEnter={() => setActive(flatIdx)}
                        onClick={() => onSuggestionSelect(it)}>
                      <span className="tok">{it.label}</span>
                      {it.hint && <span className="hint">{it.hint}</span>}
                      {it.count != null && <span className="count">{it.count}</span>}
                    </li>
                  );
                })}
              </React.Fragment>
            );
          })}
          <div className="search-suggestions-footer">
            <span className="keys">
              <span><span className="g-kbd">↑</span><span className="g-kbd">↓</span> navigate</span>
              <span><span className="g-kbd">↵</span> select</span>
              <span><span className="g-kbd">Esc</span> close</span>
            </span>
            <span>prefix <span className="g-kbd">−</span> to exclude</span>
          </div>
        </ul>
      )}
    </div>
  );
}

// Token-based filter — used by Library
function filterFilesByTokens(files, tokens) {
  if (!tokens.length) return files;
  return files.filter(f => {
    for (const t of tokens) {
      let matches;
      if (t.ns) {
        matches = f.tags.includes(`${t.ns}:${t.val}`);
      } else {
        // valueless: must match an exact valueless tag, or substring of any tag / name
        matches = f.tags.includes(t.val) || f.name.toLowerCase().includes(t.val.toLowerCase()) || f.tags.some(tag => tag.toLowerCase().includes(t.val.toLowerCase()));
      }
      if (t.neg ? matches : !matches) return false;
    }
    return true;
  });
}

Object.assign(window, {SearchBar, filterFilesByTokens, parseToken, tokenToString});
